name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: theshikhaa
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push snake animation
        run: |
          mkdir -p snake-assets
          cp dist/github-contribution-grid-snake.svg snake-assets/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add snake-assets/
          git commit -m "update snake animation" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
