name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: theshikhaa
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan output || git checkout output
          rm -rf .github
          rm -rf README.md
          cp dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/theshikhaa/theshikhaa.git
          git push -u origin output --force
